version: "3"

services:

  frontend:
    image: cunal/demo-frontend:6685333069ec622c9c314b95f6df6cf8cc02afe0
    container_name: frontend
    restart: on-failure
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
    networks:
      - demo-compose-network
    environment:
      - REACT_APP_BACKEND_URI=http://localhost:9091/api/demo-backend
    ports:
      - "5000:80"

  backend:
    image: cunal/demo-backend:6685333069ec622c9c314b95f6df6cf8cc02afe0
    container_name: backend
    restart: on-failure
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
    networks:
      - demo-compose-network
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/sample-app
      - JAVA_OPTS=-Dspring.profiles.active=local-docker -Xms125m -Xmx250m
    ports:
      - "80"

  gateway:
    image: cunal/demo-gateway:6685333069ec622c9c314b95f6df6cf8cc02afe0
    container_name: gateway
    restart: on-failure
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
    networks:
      - demo-compose-network
    environment:
      - DEMO_BACKEND_SERVICE=http://backend
      - JAVA_OPTS=-Dspring.profiles.active=local-docker -Xms125m -Xmx250m
      - ZIPKIN_BASE_URL=http://jaeger:9411
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RATE_LIMIT_ENABLED=true
      - RATE_LIMIT_REPOSITORY=REDIS
      - RATE_LIMIT=4
      - RATE_LIMIT_REFRESH_INTERVAL=1
    ports:
      - "9091:80"

  mongodb:
    image: mongo:4.0.2
    container_name: mongodb
    restart: on-failure
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
    networks:
      - demo-compose-network
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017"

  redis:
    image: redis:5.0.6
    container_name: redis
    restart: on-failure
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
    networks:
      - demo-compose-network
    volumes:
      - redis_data:/data
    ports:
      - "6379"

  jaeger:
    image: jaegertracing/all-in-one:1.14
    container_name: jaeger
    restart: on-failure
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
    networks:
      - demo-compose-network
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key
    volumes:
      - jaeger_badger_data:/badger
    ports:
      - "5775:5775"
      - "6831:6831"
      - "6832:6832"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
  
  mongodb-exporter:
    image: cunal/mongodb-exporter:latest
    container_name: mongodb-exporter
    restart: on-failure
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
    networks:
      - demo-compose-network
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
    ports:
      - "9216"

networks:
  demo-compose-network:
    external:
      name: demo-compose-network

volumes:
  mongodb_data: {}
  redis_data: {}
  jaeger_badger_data: {}
