apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-cm
  namespace: k8s-demo
data:
  SIMPLE_BACKEND_SERVICE: "http://simple-backend-deployment-service"
  JAVA_OPTS: "-Dspring.profiles.active=deployment -Dserver.port=80 -Xms125m -Xmx250m"

---

apiVersion: v1
kind: Service
metadata:
  name: gateway-deployment-service
  namespace: k8s-demo
  labels:
    app: gateway-deployment
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: gateway-deployment

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: gateway-deployment
  labels:        
    app: gateway-deployment
  namespace: k8s-demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: gateway-deployment
  template: 
    metadata:
      labels:        
        app: gateway-deployment
    spec:
      containers:
        - image: cunal/demo-gateway:v0.0.2
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "400Mi"
              cpu: "400m"
            limits:
              memory: "800Mi"
              cpu: "500m"
          name: gateway-deployment
          ports: 
            - containerPort: 80
          envFrom:
          - configMapRef:
              name: gateway-cm

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: gateway-hpa
  namespace: k8s-demo
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: gateway-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
