server:
  port: 9092
  servlet:
    context-path: /api

spring:
  application:
    name: gateway
  zipkin:
    base-url: http://localhost:9411

zuul:
  routes:
    backend:
      path: /simple-backend/**
      url: http://localhost:32772/
