server:
  port: 80
  servlet:
    context-path: /api

spring:
  application:
    name: gateway
  zipkin:
    base-url: ${ZIPKIN_BASE_URL}

zuul:
  routes:
    backend:
      path: /simple-backend/**
      url: ${SIMPLE_BACKEND_SERVICE}
