version: '3'
services:

  fluentd:
    image: cunal/fluentd:v1.6-debian-1-elasticsearch
    container_name: fluentd
    networks:
      - demo-compose-network
    restart: on-failure
    ports:
      - "24224:24224"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    container_name: elasticsearch
    networks:
      - demo-compose-network
    restart: on-failure
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.2.0
    container_name: kibana
    networks:
      - demo-compose-network
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    restart: on-failure
    ports:
      - "5601:5601"

networks:
  demo-compose-network:
    external:
      name: demo-compose-network

volumes:
  elasticsearch_data: {}
