kind: PersistentVolume
apiVersion: v1
metadata:
  name: elasticsearch-volume-elasticsearch-0
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: elasticsearch-volume-elasticsearch-0
    namespace: elasticsearch-cluster
  hostPath:
    path: /data/elasticsearch/ha-0

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: elasticsearch-volume-elasticsearch-1
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: elasticsearch-volume-elasticsearch-1
    namespace: elasticsearch-cluster
  hostPath:
    path: /data/elasticsearch/ha-1

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: elasticsearch-volume-elasticsearch-2
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: elasticsearch-volume-elasticsearch-2
    namespace: elasticsearch-cluster
  hostPath:
    path: /data/elasticsearch/ha-2

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch
  namespace: elasticsearch-cluster
data:
  es-java-opts: -Xms1g -Xmx1g
  cluster-name: elasticsearch-cluster
  min-master-nodes: "2"

---

kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: elasticsearch-cluster
  labels:    
    app: elasticsearch
spec:
  selector:      
      app: elasticsearch
  ports:
    - name: http-rest
      port: 9200
    - name: transport
      port: 9300
  type: ClusterIP

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: elasticsearch-cluster
spec:
  serviceName: elasticsearch
  replicas: 3
  selector:
    matchLabels:      
      app: elasticsearch
  template:
    metadata:
      labels:        
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.0.1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 700m
          requests:
            cpu: 400m
        ports:
        - name: http-rest
          containerPort: 9200
        - name: transport
          containerPort: 9300
        readinessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - name: elasticsearch-volume
          mountPath: /usr/share/elasticsearch/data
        env:
          - name: ES_JAVA_OPTS
            valueFrom:
              configMapKeyRef:
                name: elasticsearch
                key: es-java-opts
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: cluster.name
            valueFrom:
              configMapKeyRef:
                name: elasticsearch
                key: cluster-name
          - name: discovery.seed_hosts
            value: "elasticsearch-0.elasticsearch,elasticsearch-1.elasticsearch,elasticsearch-2.elasticsearch,"
          - name: cluster.initial_master_nodes
            value: "elasticsearch-0,elasticsearch-1,elasticsearch-2,"
          - name: discovery.zen.minimum_master_nodes
            valueFrom:
              configMapKeyRef:
                name: elasticsearch
                key: min-master-nodes
      initContainers:
      - name: increase-vm-max-map
        image: busybox:latest
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox:latest
        command: ["sh", "-c", "ulimit -n 65535"]
        securityContext:
          privileged: true
      - name: volume-mount-dir-permissions
        image: busybox:latest
        command: ["sh", "-c", "chmod -R 777 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: elasticsearch-volume
          mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-volume
      labels:
        app: elasticsearch
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 500Mi
