version: '3'
services:

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    container_name: fluentd
    networks:
      - demo-network
    restart: on-failure
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "discovery.type=single-node"
    container_name: elasticsearch
    networks:
      - demo-network
    restart: on-failure
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.2.0
    container_name: kibana
    networks:
      - demo-network
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    restart: on-failure
    ports:
      - "5601:5601"

networks:
  demo-network:
    external:
      name: demo-network

volumes:
  elasticsearch_data: {}
