apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch-volume-elasticsearch-0
  namespace: elasticsearch-cluster
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
