apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-cm
  namespace: kubernetes-demo
data:
  DEMO_BACKEND_SERVICE: "http://demo-backend-deployment-service"
  JAVA_OPTS: "-Dspring.profiles.active=local-docker -Xms125m -Xmx250m"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  RATE_LIMIT_ENABLED: "false"
  RATE_LIMIT_REPOSITORY: "REDIS"
  RATE_LIMIT: "10"
  RATE_LIMIT_REFRESH_INTERVAL: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: gateway-deployment-service
  namespace: kubernetes-demo
  labels:
    app: gateway-deployment
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: gateway-deployment

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: gateway-deployment
  labels:        
    app: gateway-deployment
  namespace: kubernetes-demo
spec: 
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: gateway-deployment
  template: 
    metadata:
      labels:        
        app: gateway-deployment
    spec:
      containers:
        - image: cunal/demo-gateway:6685333069ec622c9c314b95f6df6cf8cc02afe0
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /api/actuator/health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            requests:
              cpu: "800m"
            limits:
              cpu: "1000m"
          name: gateway-deployment
          ports: 
            - containerPort: 80
          envFrom:
          - configMapRef:
              name: gateway-cm

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: gateway-hpa
  namespace: kubernetes-demo
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: gateway-deployment
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 10
