version: '3'
services:

  prometheus:
    image: prom/prometheus:v2.12.0
    container_name: prometheus
    restart: on-failure
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
    networks:
      - demo-compose-network
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'

  nodeexporter:
    image: prom/node-exporter:v0.18.1
    container_name: nodeexporter
    restart: on-failure
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
    networks:
      - demo-compose-network
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
  
  cadvisor:
    image: google/cadvisor:v0.33.0
    container_name: cadvisor
    restart: on-failure
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
    networks:
      - demo-compose-network
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup:/cgroup:ro # only for Linux
    ports:
      - "8070:8080"
    labels:
      org.label-schema.group: "monitoring"

  grafana:
    image: grafana/grafana:6.3.6
    container_name: grafana
    restart: on-failure
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
    networks:
      - demo-compose-network
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/setup.sh:/setup.sh
    entrypoint: /setup.sh
    ports:
      - "4000:3000"

networks:
  demo-compose-network:
    external:
      name: demo-compose-network

volumes:
  prometheus_data: {}
  grafana_data: {}
