{
 "title": "Namespace Resource Usage & Quotas",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Requests by Namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) by (namespace)"
    }
   ]
  },
  {
   "title": "CPU Usages by Namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",namespace!=\"\"}[1m])) by (namespace)"
    }
   ]
  },
  {
   "title": "Memory Usages by Namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name!=\"POD\",container_name!=\"\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Memory Requests by Namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) by (namespace)"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes Cluster Monitoring",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(machine_memory_bytes{},kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  { "title": "Node Wide Resource Usages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}[1m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}) / sum (container_fs_limit_bytes{container_name!=\"POD\",device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\",container_name!=\"POD\"})"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes Namespace Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "pod",
    "label": "pods",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Namespace Based CPU and Ram Usages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Memory Usage by Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\", namespace=~\"^$namespace$\", pod_name=~\"^$pod$\"}) by (pod_name)",
     "legendFormat": " {{ pod_name }} "
    }
   ]
  },
  {
   "title": "CPU Usage by Pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$namespace$\",container_name!=\"POD\", pod_name=~\"^$pod$\"}[1m])) by (pod_name)",
     "legendFormat": " {{ pod_name }} "
    }
   ]
  },
  { "title": "Disk Usage by Pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Persistent Volume Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (\n  container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",container_name!=\"POD\", namespace=~\"^$namespace$\", pod_name=~\"^$pod$\"}\n)\n/\nsum (\n  sum (kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=~\"^$namespace$\", persistentvolumeclaim=~\"^$volume$\"})\n) * 100"
    }
   ]
  },
  {
   "title": "Current Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (\n  container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",container_name!=\"POD\", namespace=~\"^$namespace$\", pod_name=~\"^$pod$\"}\n) by (pod_name, namespace)"
    }
   ]
  },
  {
   "title": "Total Available Disk Size",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (\n  sum (kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=~\"^$namespace$\", persistentvolumeclaim=~\"^$volume$\"})\n) by (persistentvolumeclaim, namespace)"
    }
   ]
  }
 ]
}